name: catchu
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

# FIREBASE PACKAGES
dependencies:
  uuid: ^4.3.1
  path: ^1.9.0
  http: ^1.2.1
  path_provider: ^2.1.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  camera: ^0.10.5
  image_picker: ^1.0.4
  geolocator: ^14.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5

  firebase_core: ^3.13.0 # Core Firebase functionality
  cloud_firestore: ^5.6.6 # Firestore database
  firebase_auth: ^5.5.2 # Firebase Authentication
  firebase_storage: ^12.4.5 # Firebase Storage for file uploads
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/jawa.png
    - assets/images/LocationImage.png
    - assets/images/LogoCatchURules.png

flutter_native_splash:
  color: "#FDFAF6"
  image: assets/images/CatchU_Logo.png
  android: true
  ios: true
  fullscreen: true
