// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpIAp_3toinNiwbQ7xeDKF8ieToEGVYsI',
    appId: '1:367797428924:web:8b894d02f9c7aa085b66b9',
    messagingSenderId: '367797428924',
    projectId: 'catchu-datingapp',
    authDomain: 'catchu-datingapp.firebaseapp.com',
    storageBucket: 'catchu-datingapp.firebasestorage.app',
    measurementId: 'G-NTW6FLXEXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCl8ChRYqFDLHuOz6LItgzViCcyj9w7Y',
    appId: '1:367797428924:android:34cf4c6b0ce902b15b66b9',
    messagingSenderId: '367797428924',
    projectId: 'catchu-datingapp',
    storageBucket: 'catchu-datingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWhcE_bm1rsduH9dnEgjM0JFoOrJuDyU4',
    appId: '1:367797428924:ios:c75e42aa9cf88cab5b66b9',
    messagingSenderId: '367797428924',
    projectId: 'catchu-datingapp',
    storageBucket: 'catchu-datingapp.firebasestorage.app',
    iosBundleId: 'com.example.catchu',
  );
}
